### PR TITLE
Set noexpandtab

### PR DESCRIPTION
**Pull request by zakuro9715**

### CODE REVIEW

**Comment by cheap-glitch** [comment]
Sorry, but this setting is a personal preference and therefore doesn't belong in this plugin. You can add this line in your `.vimrc` to get the same effect:
```vim
autocmd FileType vlang setlocal noexpandtab

```

**Comment by zakuro9715** [comment]
@cheap-glitch 
> You can add this line in your .vimrc to get the same effect:

Yes. I'm setting noexpandtab in my personal preference.

But this is not only personal problem. noexpandtab is official style because v fmt replace space tab with tab and vlib uses tab . So I think this plugin should use noexpandtab.

**Comment by cheap-glitch** [comment]
> noexpandtab is official style because v fmt replace space tab with tab and vlib uses tab .

But choosing to follow the official style or not is a matter of preference :)

**Comment by zakuro9715** [comment]
I understand

**Pull request closed without merging**
